app/events/models.py
from app.extensions.database import db, CRUDMixin

class event(db.Model,CRUDMixin):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50))
    date = db.Column(db.Integer)
    desc =db.Column(db.String(1024))
    # event_date = db.relationship('event_date', backref='event', uselist=False, lazy=True)
    # event_discription = db.relationship('event_discription', backref='event', uselist=False, lazy=True)


# class event_date(db.Model,CRUDMixin):
#     id = db.Column(db.Integer, primary_key=True)
#     event_date = db.Column(db.Integer)
#     event_id = db.Column(db.Integer, db.ForeignKey('event.id'))

# class event_discription(db.Model,CRUDMixin):
#     id = db.Column(db.Integer, primary_key=True)
#     event_discription = db.Column(db.String(250))
#     event_id = db.Column(db.Integer, db.ForeignKey('event.id'))

app/users/models.py
from app.extensions.database import db, CRUDMixin



class User(db.Model,CRUDMixin):
  id = db.Column(db.Integer, primary_key=True)
  email = db.Column(db.String(80), index=True, unique=True)
  password = db.Column(db.String(80))


#class email(db.Model, CRUDMixin):
#    id = db.Column(db.Integer, primary_key=True)
#    email = db.Column(db.String(80))
#    password = db.relationship('Password', backref='email', uselist=False, lazy=True)

#class Password(db.Model,CRUDMixin):
#    id = db.Column(db.Integer, primary_key=True)
#    password = db.Column(db.String(25))
#    email_id = db.Column(db.Integer, db.ForeignKey('email.id'))

#class event_title(db.Model,CRUDMixin):
 #   id = db.Column(db.Integer, primary_key=True)
  #  event_title = db.Column(db.String(50), unique=True)
   # event_date = db.Column(db.Integer(8), unique=True)
    #event_discription =db.Column(db.String(250), unique=True)
    #event_date = db.relationship('event_date', backref='event_title', uselist=False, lazy=True)
    #event_discription = db.relationship('event_discription', backref='event_title', uselist=False, lazy=True)


#class event_date(db.Model,CRUDMixin):
 #   id = db.Column(db.Integer, primary_key=True)
  #  event_date = db.Column(db.Integer(8))
  #  event_tilte_id = db.Column(db.Integer, db.ForeignKey('event_title.id'))
#class event_discription(db.Model,CRUDMixin):
 #   id = db.Column(db.Integer, primary_key=True)
  #  event_discription = db.Column(db.String(250))
   # event_title_id = db.Column(db.Integer, db.ForeignKey('event_title.id'))

app/__init__.py
#from .users import users
from . import events

app/api/__init__.py
from . import routes

app/api/routes.py
from flask import Blueprint, jsonify, request
from .services.serialize_events import serialize_events
from app.events.models import event
from os import environ


blueprint = Blueprint('api',__name__)

@blueprint.get('/api/v1/events')
def events():
    if environ.get('API_KEY') == request.header.get('X-API-KEY'):
        events=event.query.all()

        return jsonify(
         serialize_events(events)
        )
    else:
        return jsonify({'error': 'Invalid API key'}), 401


# def serialize_events(events):
#     events_list = []

#     for event in events:
#         events_list.append({
#             'id' : event.id,
#             'title' : event,
#             'date' : event_date.strftime('%Y-%m-%d'),
#             'discription' : event_discription
#         })
#     return events_list

app/app.py
from flask import Flask, Blueprint
from app.extensions.database import db, migrate
# from app.events.models import event
# from app.users.models import users
from . import events, api, users

from app.events.routes import blueprint as events_blueprint
from app.api.routes import blueprint as api_blueprint

def create_app():
  app = Flask(__name__)
  app.config.from_object('app.config')
  register_extensions(app)
  register_blueprints(app)

  return app

def register_blueprints(app: Flask):
  app.register_blueprint(events_blueprint)
  app.register_blueprint(users.routes.blueprint)
  app.register_blueprint(api_blueprint)

def register_extensions(app:Flask):
  db.init_app(app)
  with app.app_context():
      from app.events.models import event
      db.create_all()
      migrate.init_app(app, db, compare_type=True)

app/events/__init__.py
# from . import models, routes


app/events/routes.py
from flask import Blueprint, Flask, render_template, redirect, url_for, send_file, request, current_app
from .models import event
#from app.events.models import event, event_date, event_discription, events
#from .services.create_event import create_event
from app.extensions.database import db


blueprint = Blueprint('events',__name__)

@blueprint.route('/events')
def get_events():
  events = event.query.all()
  page_number = request.args.get('page', 1, type=int)
  events_pagination = event.query.paginate(page=page_number, max_per_page=current_app.config['EVENTS_MAX_PER_PAGE'])
  return render_template('events.html',events_pagination=events_pagination, events=events)

@blueprint.route('/register', methods=('GET','POST'))
def post_events():

  if request.method == 'POST':
    new_event=event(
      name=request.form['event'],
      date=request.form['event_date'],
      desc=request.form['event_discription']
    )
    print(db)
    db.session.add(new_event)
    db.session.commit()
    print("new event is saved", new_event)
    return redirect(url_for('events.get_events'))
  return render_template('register.html')


@blueprint.route('/')
def index():
  return render_template('index.html')

@blueprint.route('/register')
def register():
  return render_template('register.html')

def register_blueprint(app: Flask):
   #app.register_blueprint(users.routes.blueprint)
   app.register_blueprint(event.routes.blueprint)



app/users/__init__.py
from . import models, routes

app/users/routes.py
from flask import Blueprint, render_template, request, url_for,redirect
from app.users.models import User
from werkzeug.security import generate_password_hash, check_password_hash
blueprint = Blueprint('user', __name__)


@blueprint.get('/register_acc')
def get_register_acc():
   return render_template('users/register_acc.html')

@blueprint.post('/register_acc')
def post_register_acc():
  try:
    if request.form.get('password') != request.form.get('password_confirmation'):
        return render_template('users/register_acc.html', error='The password confirmation must match the password.')
    elif User.query.filter_by(email=request.form.get('email')).first():
      return render_template('users/register_acc.html', error='The email adress is already registered')

    user = User(
      email=request.form.get('email'),
      password=generate_password_hash(request.form.get('password'))
    )
    user.save()
    return redirect(url_for('events.events'))
  except Exception as error_meassage:
    error= error_meassage or 'An error ocurred while creating a user. Please make sure to enter valid data'
    return render_template('users/register_acc.html',error=error)

@blueprint.get('/login')
def get_login():
 return render_template('users/login.html')

@blueprint.post('/login')
def post_login():
  try:
    user = User.query.filter_by(email=request.form.get('email')).first()

    if not user:
      raise Exception('No user with the given email address was found.')
    elif not check_password_hash(user.password, request.form.get('password')):
      raise Exception('The password does not appear to be correct.')
    
    return redirect(url_for('events.events'))
  except Exception as error_message:
    error = error_message or 'An error occured while logging in. Please verify your email and password'
    return render_template('users/login.html', error=error)

@blueprint.get('/logout')
def logout():
  return 'User logged out'





app/templates/base.html
<!DOCTYPE html>
<head>
  <html lang="en">
<head>
  {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  {% endblock %}
</head>
</head>
<body>
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                
                <menuitem><a href="{{ url_for('events.get_events') }}"><button type="button">Events</button></a></menuitem>
                <menuitem><a href="{{ url_for('events.register') }}"><button type="button">Register</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2></h2>
        
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
</body>

app/templates/error.html
{% if error %}
  <p style="color: tomato;">{{ error }}</p>
{% endif %}

app/templates/events.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                
                <menuitem><a href="{{ url_for('events.index') }}"><button type="button">Home</button></a></menuitem>
                <menuitem><a href="{{ url_for('events.register') }}"><button type="button">Register</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
      <form method="POST">
        {% for event in events %}
        <p>{{event.name}}</p>
        <p>{{event.date}}</p>
        <p>{{event.desc}}</p>
        <!-- <li>
          <label for="event_{{ event.id }}">{{event.desc}}</label>
          <label for="event_{{ event.name }}">{{event.name}}</label>
          <label for="event_{{ event.date }}">{{event.date}}</label>
        </li> -->
        {%endfor%}

        <!-- {% for event_date in event_dates %}

        <li>
          <label for="event_date_{{ event_date.id }}">{{event.event_date}}</label></s>
          <input type="number"event_date="{{user.slug}}" id="event_date_{{event_date.id}}"min="0" value="0">
        </li>
        {%endfor%}

        {% for event_discription in event_discriptions %}

        <li>
          <label for="event_discription{{ event_discription.id }}">{{event.event_discription}}</label></s>
          <input type="number"event_discription="{{user.slug}}" id="event_discription_{{event_discription.id}}"min="0" value="0">
        </li>
        {%endfor%}
           -->
          <p>
            {% if events_pagination.prev_num %}
            <a href="{{url_for('events.events',page=events_pagination.pref_num) }}">Next Page</a>
            {%else%}
            <span> Previuos Page </span>
            {% endif %}
            <span> - </span>
            {% if events_pagination.next_num %}
              <a href="{{ url_for('events.events', page=events_pagination.next_num) }}">Next Page</a>
            {% else%}
              <span>Next Page</span>
            {% endif %}
          </p>
      </form>
      </div>
      <a href="{{ url_for('events.register') }}"><button type="button">Register your event</button></a>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
</body>

app/templates/index.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                <menuitem><a href="{{ url_for('events.get_events') }}"><button type="button">Events</button></a></menuitem>
                <menuitem><a href="{{ url_for('events.register') }}"><button type="button">Register your event</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2>Start to explore your area and connect with people</h2>
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
</body>

app/templates/login.html
<!DOCTYPE html>
<head>
  <html lang="en">
<head>
  {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  {% endblock %}
</head>
</head>
<body>
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                
                <menuitem><a href="{{ url_for('events.get_events') }}"><button type="button">Events</button></a></menuitem>
                <menuitem><a href="{{ url_for('events.register') }}"><button type="button">Register</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2></h2>
        
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
</body>

app/templates/register.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                <menuitem><a href="{{ url_for('events.index') }}"><button type="button">Home</button></a></menuitem>
                <menuitem><a href="{{ url_for('events.get_events') }}"><button type="button">Events</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2>Register your event</h2>
        <form method="POST">
          <p>
            <div>
              <label for="event"></label>
              <input type="text" name="event" id="event" placeholder="your event name">
            </div>
          </p>
          <p>
            <div>
              <label for="event_date"></label>
              <input type="integer" name="event_date" id="event_date"  placeholder="dd.mm.yyyy">
            </div>
          </p>
          <p>
            <div>
              <label for="event_discription"></label>
              <input type="text" name="event_discription" id="event_discription" placeholder="your event discription">
            </div>
          </p>
          <p>
            <div>
              <input type="submit" value="register">
            </div>
          </p>  
        </form>
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
</body>

app/templates/users/login.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
{% block body %}
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                <menuitem><a href="{{ url_for('events.index') }}"><button type="button">Home</button></a></menuitem>
                <menuitem><a href="{{ url_for('events.get_events') }}"><button type="button">Events</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2>Register</h2>
        <form method="POST">
          
            <div>
              <label for="email">Email</label>
              <input type="email" name="email" id="email" required>
            </div>
            <div>
              <label for="password">Password</label>
              <input type="password" name="password" id="password" required>
            </div>
           
            <input type="submit" value="Login">

        </form>
        {% if error %}
        <p style="color: tomato;">{{ error }}</p>
        {% endif %}
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
  {% endblock %}

app/templates/users/register_acc.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
{% block body %}
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                <menuitem><a href="{{ url_for('events.index') }}"><button type="button">Home</button></a></menuitem>
                <menuitem><a href="{{ url_for('events.get_events') }}"><button type="button">Events</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2>Register</h2>
        <form method="POST">
          
            <div>
              <label for="email">Email</label>
              <input type="email" name="email" id="email" required>
            </div>
            <div>
              <label for="password">Password</label>
              <input type="password" name="password" id="password" required>
            </div>

            <div>
                <label for="password_confirmation">Password Confirmation</label>
                <input type="password" name="password_confirmation" id="password_confirmation" required>
            </div>
           
            <input type="submit" value="Sign Up">
        </form>
      {% if error %}
      <p style="color: tomato;">{{ error }}</p>
      {% endif %}     
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
  {% endblock %}